# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cad28db769e6c0f3973e4c0b544398d9509f714399d2d32280cd742ae175d382683a11bc61ba3fffdb7477be4f035a8c40932aeca1a23c51bb871316f6aa075

test:
  secret_key_base: fe682952386c194c9151e8de8399f2100c5fc787919658abb6cc826cad3f424f658ca10b0d8b9fb148012ee0d277d72cc29841f40fc4c83bbdbb181f383a6c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
